### ISSUE TITLE
Review s42

### ISSUE THREAD

**Issue by lausek** [MarcoWojaczek/dhbw_se_basis#1]
Sieht gut aus. Eine Sache aber noch - das hier ist zu kompliziert. `setCommand` wird bisher nur innerhalb von `Button` aufgerufen, was den setter eigentlich überflüssig macht.

https://github.com/MarcoWoja/se_basis/blob/1ed93ccbdf7778f65234d6689934d4494d7b3f93/b42/src/main/java/Button.java#L15-L30

Hier hast du Zugriff auf die `DivingWatch`. Setz die Commands an dieser Stelle: https://github.com/MarcoWoja/se_basis/blob/1ed93ccbdf7778f65234d6689934d4494d7b3f93/b42/src/main/java/Time.java#L1-L5

```java
divingWatch.getButton1().setCommand(new LeftBofftleCommand(divingWatch));
```

Dann kannst du alles, was du bisher in `Button.press` stehen hast rauswerfen und es einfach zu `command.press()` ändern. Das toggeln machst du auch einfach zu einem eigenen Command und setzt es einmal initial im constructor der `DivingWatch`

**Comment by MarcoWojaczek** [comment]
Okay danke, ja mit dem setCommand() war ich mir auch nicht sicher ob das so Sinn macht als ichs bearbeitet hab, die Variante is besser :)
